# Generated by Django 3.2 on 2021-04-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('unit', models.CharField(max_length=5)),
                ('price', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
